// Board layout: five equal columns -- weather, then four train columns.
//
//   ┌─────────┬─────────┬─────────┬─────────┬─────────┐
//   │   78°   │  (2/3)  │  (4/5)  │   (A)   │  (B/Q)  │  bullet
//   │ 82°/71° │ Nevins  │ Nevins  │Schermer.│ DeKalb  │  station
//   │   ☂     │    7    │    1    │    3    │    0    │  next train, big
//   │  60%    │  15 24  │   8 15  │  12 19  │   9 17  │  following trains
//   ├─────────┴─────────┴─────────┴─────────┴─────────┤
//   │ alert ticker                              3:05 PM│
//   └───────────────────────────────────────────────────┘

#include <stdio.h>
#include <string.h>
#include <math.h>

#include "display.h"
#include "EPD.h"
#include "config.h"
#include "helvfont.h"
#include "stopnames.h"

namespace {

constexpr int SCREEN_W   = 792;
constexpr int SCREEN_H   = 272;
// NUM_TRAIN_COLS is now a runtime value (from the fetched config), so the column
// count and width are computed per-render inside displayRender (numCols/colW).

constexpr int BULLET_CY  = 40;
constexpr int BULLET_R   = 31;
constexpr int STATION_TOP = 72;    // destination band: just below the bullet...
constexpr int STATION_BOT = 101;   // ...to just above the big digits
constexpr int STATION_BAND = STATION_BOT - STATION_TOP;
constexpr int BIG_Y      = 102;    // helv40b rows 102..142
constexpr int ROW_Y[3]   = {150, 180, 210};   // helv28b rows for arrivals 2-4
constexpr int RULE_Y     = 244;
constexpr int BOTTOM_Y   = 250;    // helv18 ticker/clock line

// Destination label auto-fit ladder (ascending; baked by genfont.py). The
// largest whose text fits the column width and the vertical band is used, but
// never smaller than STATION_FLOOR_IDX (helv15) -- labels too wide there are
// truncated instead of shrinking the whole set below 15px.
static const HelvFont* const STATION_FONTS[] = {&helv11, &helv15, &helv19, &helv23};
constexpr int NUM_STATION_FONTS = 4;
constexpr int STATION_FLOOR_IDX = 1;   // helv15 -- the minimum size

// Direction arrows indexed by travelDir(): 0=N, 1=E, 2=S, 3=W.
static const SymBitmap* const ARROWS[4] = {&icon_arr_n, &icon_arr_e, &icon_arr_s, &icon_arr_w};

// ---- Helvetica bitmap renderer (fonts generated by genfont.py) ----

int helvGlyph(const HelvFont& f, char c) {
  const char* p = strchr(f.charset, c);
  return p ? (int)(p - f.charset) : -1;
}

int helvCharW(const HelvFont& f, char c) {
  int i = helvGlyph(f, c);
  return i < 0 ? 0 : f.widths[i];
}

int helvTextW(const HelvFont& f, const char* s) {
  int w = 0;
  for (; *s; s++) w += helvCharW(f, *s);
  return w;
}

// Paints only foreground pixels; returns the advance.
int helvDrawChar(const HelvFont& f, int x, int y, char c, int color) {
  int i = helvGlyph(f, c);
  if (i < 0) return 0;
  int w = f.widths[i];
  int wbytes = (w + 7) / 8;
  const uint8_t* d = f.data + f.offsets[i];
  for (int row = 0; row < f.height; row++)
    for (int xb = 0; xb < wbytes; xb++) {
      uint8_t b = d[row * wbytes + xb];
      for (int bit = 0; b && bit < 8; bit++, b <<= 1)
        if (b & 0x80) Paint_SetPixel(x + xb * 8 + bit, y + row, color);
    }
  return w;
}

void helvDraw(const HelvFont& f, int x, int y, const char* s, int color) {
  for (; *s; s++) x += helvDrawChar(f, x, y, *s, color);
}

void helvCentered(const HelvFont& f, int cx, int y, const char* s, int color) {
  helvDraw(f, cx - helvTextW(f, s) / 2, y, s, color);
}

void drawSymbol(const SymBitmap& s, int x, int y, int color) {
  int wbytes = (s.w + 7) / 8;
  for (int row = 0; row < s.h; row++)
    for (int xb = 0; xb < wbytes; xb++) {
      uint8_t b = s.data[row * wbytes + xb];
      for (int bit = 0; b && bit < 8; bit++, b <<= 1)
        if (b & 0x80) Paint_SetPixel(x + xb * 8 + bit, y + row, color);
    }
}

// Minutes until epoch t; negative means already gone.
long minutesUntil(uint32_t t, time_t now) {
  if ((time_t)t <= now) return ((time_t)t >= now - 45) ? 0 : -1;
  return (t - now) / 60;
}

// Find a stop by id (strips the N/S suffix, binary-searches STOP_NAMES, which
// genstops.py sorts by id). Returns the entry (name + lat/lon) or nullptr.
const StopName* stopFind(const char* stopId) {
  if (!stopId || !stopId[0]) return nullptr;
  char base[8];
  size_t n = strlen(stopId);
  if (n && (stopId[n - 1] == 'N' || stopId[n - 1] == 'S')) n--;
  if (n >= sizeof(base)) n = sizeof(base) - 1;
  memcpy(base, stopId, n);
  base[n] = '\0';
  int lo = 0, hi = (int)STOP_NAMES_COUNT - 1;
  while (lo <= hi) {
    int mid = (lo + hi) / 2;
    int c = strcmp(STOP_NAMES[mid].id, base);
    if (c == 0) return &STOP_NAMES[mid];
    if (c < 0) lo = mid + 1;
    else hi = mid - 1;
  }
  return nullptr;
}

const char* stopName(const char* stopId) {
  const StopName* s = stopFind(stopId);
  return s ? s->name : "";
}

// Compass heading from one stop to another, snapped to the dominant axis:
// 0=N, 1=E, 2=S, 3=W, or -1 if either stop's coordinates are unknown. The
// feed only encodes N/S; this recovers true E/W (e.g. the 7 to Hudson Yards).
int travelDir(const char* fromId, const char* toId) {
  const StopName* a = stopFind(fromId);
  const StopName* b = stopFind(toId);
  if (!a || !b) return -1;
  float dN = b->lat - a->lat;
  float dE = (b->lon - a->lon) * cosf((a->lat + b->lat) * 0.5f * 0.017453292f);
  if (fabsf(dN) >= fabsf(dE)) return dN >= 0 ? 0 : 2;
  return dE >= 0 ? 1 : 3;
}

constexpr char DEG = '\xb0';

void hour12(int h, char* buf, size_t sz) {
  snprintf(buf, sz, "%d%s", ((h + 11) % 12) + 1, h < 12 ? "AM" : "PM");
}

// Icon + text, centered as a unit and vertically centered on cy.
void iconRow(int cx, int cy, const SymBitmap& ic, const char* text,
             const HelvFont& font, int gap = 5) {
  int tw = helvTextW(font, text);
  int x0 = cx - (ic.w + gap + tw) / 2;
  drawSymbol(ic, x0, cy - ic.h / 2, BLACK);
  helvDraw(font, x0 + ic.w + gap, cy - font.height / 2, text, BLACK);
}

// Weather column: big feels-like temperature, then rows -- wind gusts, rain
// (only if likely), UV, and Citi Bike e-bikes (only if available) -- spread
// evenly below the temperature.
void drawWeather(int cx, const WeatherInfo& wx, int ebikes) {
  if (!wx.valid) {
    helvCentered(helv28b, cx, 30, "--", BLACK);
    return;
  }
  char buf[24];
  snprintf(buf, sizeof(buf), "%d%c", wx.feels, DEG);
  helvCentered(helv40b, cx, 16, buf, BLACK);

  const SymBitmap* icons[4];
  char texts[4][20];
  int n = 0;
  icons[n] = &icon_wind; snprintf(texts[n], sizeof(texts[0]), "%d mph", wx.gusts); n++;
  if (wx.rainHour >= 0) {
    char hb[8]; hour12(wx.rainHour, hb, sizeof(hb));
    icons[n] = &sym_rain;
    snprintf(texts[n], sizeof(texts[0]), "%d%% %s", wx.rainProb, hb); n++;
  }
  icons[n] = &sym_sun; snprintf(texts[n], sizeof(texts[0]), "%d %s", wx.uv, wx.uvLevel); n++;
  if (ebikes >= 0) { icons[n] = &icon_ebike; snprintf(texts[n], sizeof(texts[0]), "%d", ebikes); n++; }

  const int top = 66, bot = RULE_Y - 12;    // 66 .. 232
  for (int i = 0; i < n; i++) {
    int cy = top + (bot - top) * (2 * i + 1) / (2 * n);
    iconRow(cx, cy, *icons[i], texts[i], helv18);
  }
}

// Copy at most the first three (space-separated) words of src into dst.
void threeWords(const char* src, char* dst, size_t dstSize) {
  size_t j = 0;
  int words = 0;
  bool prevSpace = true;
  for (size_t i = 0; src[i]; i++) {
    bool sp = (src[i] == ' ');
    if (!sp && prevSpace && ++words > 3) break;   // start of a 4th word
    prevSpace = sp;
    if (j < dstSize - 1) dst[j++] = src[i];
  }
  while (j > 0 && dst[j - 1] == ' ') j--;          // trim trailing space
  dst[j] = '\0';
}

// The largest ladder font at which EVERY label fits the column width + band,
// so all columns share one size (the size of the most-constrained label).
const HelvFont* uniformStationFont(const char labels[][48], int count, int colW) {
  int best = NUM_STATION_FONTS - 1;
  for (int c = 0; c < count; c++) {
    int idx = 0;
    for (int k = 0; k < NUM_STATION_FONTS; k++) {
      const HelvFont* f = STATION_FONTS[k];
      if (f->height <= STATION_BAND && helvTextW(*f, labels[c]) <= colW - 8) idx = k;
    }
    if (idx < best) best = idx;
  }
  if (best < STATION_FLOOR_IDX) best = STATION_FLOOR_IDX;   // 15px minimum
  return STATION_FONTS[best];
}

}  // namespace

void displayRender(const RouteArrivals* routes, size_t nRoutes, time_t now,
                   const RouteAlert* alerts, const WeatherInfo& wx,
                   int rotation, const char* clock12, int ebikes) {
  Paint_Clear(WHITE);

  // Column count + width are driven by the runtime config (weather + N trains).
  const int numCols = NUM_TRAIN_COLS + 1;
  const int colW = SCREEN_W / numCols;

  drawWeather(colW / 2, wx, ebikes);

  // Destination labels first (next train's terminal, or the fallback), each
  // capped to 3 words, so they can share one uniform size -- the largest at
  // which every column's label fits.
  char labels[MAX_COLS][48];
  int dir[MAX_COLS];
  for (int col = 0; col < NUM_TRAIN_COLS; col++) {
    const ColumnConfig& cc = COLUMNS[col];
    long bestMin = 100;                     // display caps at 99 min
    const char* bestDest = "";
    const char* bestDestId = "";
    for (uint8_t ri = 0; ri < cc.nRoutes; ri++) {
      const RouteArrivals& ra = routes[cc.routeIdx[ri]];
      for (uint8_t i = 0; i < ra.count; i++) {
        long m = minutesUntil(ra.times[i], now);
        if (m < 0 || m > 99) continue;
        const char* dn = stopName(ra.dest[i]);
        if (cc.nFilter > 0) {
          bool ok = false;
          for (uint8_t k = 0; k < cc.nFilter; k++)
            if (cc.destFilter[k][0] && strcmp(cc.destFilter[k], dn) == 0) { ok = true; break; }
          if (!ok) continue;
        }
        if (m < bestMin) { bestMin = m; bestDest = dn; bestDestId = ra.dest[i]; }
      }
    }
    const char* station = (bestMin <= 99 && bestDest[0]) ? bestDest : cc.station;
    threeWords(station, labels[col], sizeof(labels[col]));
    dir[col] = (bestMin <= 99) ? travelDir(routes[cc.routeIdx[0]].stopId, bestDestId) : -1;
  }
  const HelvFont* sfont = uniformStationFont(labels, NUM_TRAIN_COLS, colW);
  int stationY = STATION_TOP + (STATION_BAND - sfont->height) / 2;

  // Alert blurbs for columns that end up with no trains to show.
  const char* blurbs[MAX_COLS];
  char fallback[MAX_COLS][44];
  int nBlurbs = 0;

  for (int col = 0; col < NUM_TRAIN_COLS; col++) {
    const ColumnConfig& cc = COLUMNS[col];
    int cx = (col + 1) * colW + colW / 2;

    // Bullet (the route label) + direction arrow to its left.
    EPD_DrawCircle(cx, BULLET_CY, BULLET_R, BLACK, 1);
    helvCentered(helv28b, cx, BULLET_CY - helv28b.height / 2, cc.label, WHITE);
    if (dir[col] >= 0) {
      const SymBitmap& a = *ARROWS[dir[col]];
      drawSymbol(a, cx - BULLET_R - 6 - a.w, BULLET_CY - a.h / 2, BLACK);
    }

    // Destination label (precomputed, one uniform size). Truncate if it still
    // overflows at that size.
    char stbuf[48];
    strncpy(stbuf, labels[col], sizeof(stbuf) - 1);
    stbuf[sizeof(stbuf) - 1] = '\0';
    for (int len = strlen(stbuf); len > 0 && helvTextW(*sfont, stbuf) > colW - 8; )
      stbuf[--len] = '\0';
    helvCentered(*sfont, cx, stationY, stbuf, BLACK);

    // Merge this column's routes into one sorted minutes list, remembering
    // each arrival's route. A non-empty destFilter keeps only trains bound for
    // those destinations.
    long mins[ARRIVALS_SHOWN];
    const char* who[ARRIVALS_SHOWN];
    int n = 0;
    for (uint8_t ri = 0; ri < cc.nRoutes; ri++) {
      const RouteArrivals& ra = routes[cc.routeIdx[ri]];
      for (uint8_t i = 0; i < ra.count; i++) {
        long m = minutesUntil(ra.times[i], now);
        if (m < 0 || m > 99) continue;
        if (cc.nFilter > 0) {
          const char* dn = stopName(ra.dest[i]);
          bool ok = false;
          for (uint8_t k = 0; k < cc.nFilter; k++)
            if (cc.destFilter[k][0] && strcmp(cc.destFilter[k], dn) == 0) { ok = true; break; }
          if (!ok) continue;
        }
        int pos = n < ARRIVALS_SHOWN ? n : ARRIVALS_SHOWN - 1;
        if (n == ARRIVALS_SHOWN && m >= mins[pos]) continue;
        while (pos > 0 && mins[pos - 1] > m) {
          mins[pos] = mins[pos - 1];
          who[pos] = who[pos - 1];
          pos--;
        }
        mins[pos] = m;
        who[pos] = ra.route;
        if (n < ARRIVALS_SHOWN) n++;
      }
    }

    if (n == 0) {
      EPD_DrawRectangle(cx - 16, BIG_Y + 18, cx + 16, BIG_Y + 22, BLACK, 1);
      helvCentered(helv18, cx, ROW_Y[0] + 4, "no service", BLACK);

      const char* blurb = nullptr;
      for (uint8_t ri = 0; ri < cc.nRoutes && !blurb; ri++) {
        const char* route = routes[cc.routeIdx[ri]].route;
        for (size_t a = 0; a < nRoutes; a++)
          if (strcmp(alerts[a].route, route) == 0 && alerts[a].text[0]) {
            blurb = alerts[a].text;
            break;
          }
      }
      if (!blurb) {
        snprintf(fallback[nBlurbs], sizeof(fallback[0]),
                 "No [%s] trains scheduled right now", cc.label);
        blurb = fallback[nBlurbs];
      }
      bool dup = false;
      for (int b = 0; b < nBlurbs; b++)
        if (strcmp(blurbs[b], blurb) == 0) dup = true;
      if (!dup) blurbs[nBlurbs++] = blurb;
      continue;
    }

    // Each arrival: minutes in a large font, then a smaller "min" (helv18,
    // and the route tag on two-route columns) baseline-aligned beside it, the
    // pair centered in the column: big "5" + small "min (B)".
    bool tag = cc.nRoutes > 1;
    char num[8], suffix[12];
    for (int i = 0; i < n; i++) {
      const HelvFont& numFont = (i == 0) ? helv40b : helv28b;
      int y = (i == 0) ? BIG_Y : ROW_Y[i - 1];
      int gap = (i == 0) ? 6 : 4;
      snprintf(num, sizeof(num), "%ld", mins[i]);
      if (tag) snprintf(suffix, sizeof(suffix), "min (%s)", who[i]);
      else     snprintf(suffix, sizeof(suffix), "min");
      int wn = helvTextW(numFont, num), ws = helvTextW(helv18, suffix);
      int xx = cx - (wn + gap + ws) / 2;
      helvDraw(numFont, xx, y, num, BLACK);
      helvDraw(helv18, xx + wn + gap, y + (numFont.height - helv18.height), suffix, BLACK);
    }
  }

  // Column separators + bottom rule.
  for (int c = 1; c < numCols; c++)
    EPD_DrawLine(c * colW, 10, c * colW, RULE_Y - 8, BLACK);
  EPD_DrawLine(0, RULE_Y, SCREEN_W - 1, RULE_Y, BLACK);

  // Bottom line: alert ticker on the left, clock on the right.
  int clockW = clock12 ? helvTextW(helv18, clock12) : 0;
  if (clock12)
    helvDraw(helv18, SCREEN_W - clockW - 8, BOTTOM_Y, clock12, BLACK);

  if (nBlurbs > 0) {
    char line[110];
    snprintf(line, sizeof(line), "%s", blurbs[rotation % nBlurbs]);
    if (nBlurbs > 1) {
      char tag[10];
      snprintf(tag, sizeof(tag), " (%d/%d)", rotation % nBlurbs + 1, nBlurbs);
      strncat(line, tag, sizeof(line) - strlen(line) - 1);
    }
    // Truncate to fit left of the clock.
    int maxW = SCREEN_W - clockW - 32;
    int len = strlen(line);
    while (len > 0 && helvTextW(helv18, line) > maxW) line[--len] = '\0';
    helvDraw(helv18, 8, BOTTOM_Y, line, BLACK);
  }
}
