// Board layout: five equal columns -- weather, then four train columns.
//
//   ┌─────────┬─────────┬─────────┬─────────┬─────────┐
//   │   78°   │  (2/3)  │  (4/5)  │   (A)   │  (B/Q)  │  bullet
//   │ 82°/71° │ Nevins  │ Nevins  │Schermer.│ DeKalb  │  station
//   │   ☂     │    7    │    1    │    3    │    0    │  next train, big
//   │  60%    │  15 24  │   8 15  │  12 19  │   9 17  │  following trains
//   ├─────────┴─────────┴─────────┴─────────┴─────────┤
//   │ alert ticker                              3:05 PM│
//   └───────────────────────────────────────────────────┘

#include <stdio.h>
#include <string.h>

#include "display.h"
#include "EPD.h"
#include "config.h"
#include "helvfont.h"

namespace {

constexpr int SCREEN_W   = 792;
constexpr int SCREEN_H   = 272;
constexpr int NUM_COLS   = NUM_TRAIN_COLS + 1;      // + weather
constexpr int COL_W      = SCREEN_W / NUM_COLS;     // 158

constexpr int BULLET_CY  = 40;
constexpr int BULLET_R   = 31;
constexpr int STATION_Y  = 76;     // helv18 rows 76..94
constexpr int BIG_Y      = 102;    // helv40b rows 102..142
constexpr int ROW_Y[3]   = {150, 180, 210};   // helv28b rows for arrivals 2-4
constexpr int RULE_Y     = 244;
constexpr int BOTTOM_Y   = 250;    // helv18 ticker/clock line

// ---- Helvetica bitmap renderer (fonts generated by genfont.py) ----

int helvGlyph(const HelvFont& f, char c) {
  const char* p = strchr(f.charset, c);
  return p ? (int)(p - f.charset) : -1;
}

int helvCharW(const HelvFont& f, char c) {
  int i = helvGlyph(f, c);
  return i < 0 ? 0 : f.widths[i];
}

int helvTextW(const HelvFont& f, const char* s) {
  int w = 0;
  for (; *s; s++) w += helvCharW(f, *s);
  return w;
}

// Paints only foreground pixels; returns the advance.
int helvDrawChar(const HelvFont& f, int x, int y, char c, int color) {
  int i = helvGlyph(f, c);
  if (i < 0) return 0;
  int w = f.widths[i];
  int wbytes = (w + 7) / 8;
  const uint8_t* d = f.data + f.offsets[i];
  for (int row = 0; row < f.height; row++)
    for (int xb = 0; xb < wbytes; xb++) {
      uint8_t b = d[row * wbytes + xb];
      for (int bit = 0; b && bit < 8; bit++, b <<= 1)
        if (b & 0x80) Paint_SetPixel(x + xb * 8 + bit, y + row, color);
    }
  return w;
}

void helvDraw(const HelvFont& f, int x, int y, const char* s, int color) {
  for (; *s; s++) x += helvDrawChar(f, x, y, *s, color);
}

void helvCentered(const HelvFont& f, int cx, int y, const char* s, int color) {
  helvDraw(f, cx - helvTextW(f, s) / 2, y, s, color);
}

void drawSymbol(const SymBitmap& s, int x, int y, int color) {
  int wbytes = (s.w + 7) / 8;
  for (int row = 0; row < s.h; row++)
    for (int xb = 0; xb < wbytes; xb++) {
      uint8_t b = s.data[row * wbytes + xb];
      for (int bit = 0; b && bit < 8; bit++, b <<= 1)
        if (b & 0x80) Paint_SetPixel(x + xb * 8 + bit, y + row, color);
    }
}

// Minutes until epoch t; negative means already gone.
long minutesUntil(uint32_t t, time_t now) {
  if ((time_t)t <= now) return ((time_t)t >= now - 45) ? 0 : -1;
  return (t - now) / 60;
}

constexpr char DEG = '\xb0';

void drawWeather(int cx, const WeatherInfo& wx) {
  if (!wx.valid) {
    helvCentered(helv28b, cx, 30, "--", BLACK);
    return;
  }
  char buf[24];
  snprintf(buf, sizeof(buf), "%d%c", wx.curTemp, DEG);
  helvCentered(helv40b, cx, 24, buf, BLACK);
  snprintf(buf, sizeof(buf), "%d%c/%d%c", wx.hi, DEG, wx.lo, DEG);
  helvCentered(helv18, cx, 76, buf, BLACK);

  const SymBitmap* sym = nullptr;
  switch (wx.cond) {
    case WX_STORM: sym = &sym_storm;    break;
    case WX_RAIN:  sym = &sym_umbrella; break;
    case WX_SNOW:  sym = &sym_snow;     break;
    default: return;
  }
  drawSymbol(*sym, cx - sym->w / 2, 112, BLACK);
  snprintf(buf, sizeof(buf), "%d%%", wx.prob);
  helvCentered(helv28b, cx, 178, buf, BLACK);
}

}  // namespace

void displayRender(const RouteArrivals* routes, size_t nRoutes, time_t now,
                   const RouteAlert* alerts, const WeatherInfo& wx,
                   int rotation, const char* clock12) {
  Paint_Clear(WHITE);

  drawWeather(COL_W / 2, wx);

  // Alert blurbs for columns that end up with no trains to show.
  const char* blurbs[NUM_TRAIN_COLS];
  char fallback[NUM_TRAIN_COLS][44];
  int nBlurbs = 0;

  for (int col = 0; col < NUM_TRAIN_COLS; col++) {
    const ColumnConfig& cc = COLUMNS[col];
    int cx = (col + 1) * COL_W + COL_W / 2;

    // Bullet + station name.
    EPD_DrawCircle(cx, BULLET_CY, BULLET_R, BLACK, 1);
    helvCentered(helv28b, cx, BULLET_CY - helv28b.height / 2, cc.label, WHITE);
    helvCentered(helv18, cx, STATION_Y, cc.station, BLACK);

    // Merge this column's routes into one sorted minutes list, remembering
    // which route each arrival belongs to.
    long mins[ARRIVALS_SHOWN];
    const char* who[ARRIVALS_SHOWN];
    int n = 0;
    for (uint8_t ri = 0; ri < cc.nRoutes; ri++) {
      const RouteArrivals& ra = routes[cc.routeIdx[ri]];
      for (uint8_t i = 0; i < ra.count; i++) {
        long m = minutesUntil(ra.times[i], now);
        if (m < 0 || m > 99) continue;
        int pos = n < ARRIVALS_SHOWN ? n : ARRIVALS_SHOWN - 1;
        if (n == ARRIVALS_SHOWN && m >= mins[pos]) continue;
        while (pos > 0 && mins[pos - 1] > m) {
          mins[pos] = mins[pos - 1];
          who[pos] = who[pos - 1];
          pos--;
        }
        mins[pos] = m;
        who[pos] = ra.route;
        if (n < ARRIVALS_SHOWN) n++;
      }
    }

    if (n == 0) {
      EPD_DrawRectangle(cx - 16, BIG_Y + 18, cx + 16, BIG_Y + 22, BLACK, 1);
      helvCentered(helv18, cx, ROW_Y[0] + 4, "no service", BLACK);

      const char* blurb = nullptr;
      for (uint8_t ri = 0; ri < cc.nRoutes && !blurb; ri++) {
        const char* route = routes[cc.routeIdx[ri]].route;
        for (size_t a = 0; a < nRoutes; a++)
          if (strcmp(alerts[a].route, route) == 0 && alerts[a].text[0]) {
            blurb = alerts[a].text;
            break;
          }
      }
      if (!blurb) {
        snprintf(fallback[nBlurbs], sizeof(fallback[0]),
                 "No [%s] trains scheduled right now", cc.label);
        blurb = fallback[nBlurbs];
      }
      bool dup = false;
      for (int b = 0; b < nBlurbs; b++)
        if (strcmp(blurbs[b], blurb) == 0) dup = true;
      if (!dup) blurbs[nBlurbs++] = blurb;
      continue;
    }

    // Next train, large; following trains as plain numbers. Columns with two
    // routes tag every time with its route: "5 (B)".
    bool tag = cc.nRoutes > 1;
    char num[8], rt[8];
    snprintf(num, sizeof(num), "%ld", mins[0]);
    if (tag) {
      // Big digits + smaller "(2)" beside them, centered as a unit, tag
      // baseline-aligned with the digits.
      snprintf(rt, sizeof(rt), "(%s)", who[0]);
      int wNum = helvTextW(helv40b, num), wTag = helvTextW(helv28b, rt);
      int x0 = cx - (wNum + 6 + wTag) / 2;
      helvDraw(helv40b, x0, BIG_Y, num, BLACK);
      helvDraw(helv28b, x0 + wNum + 6, BIG_Y + (helv40b.height - helv28b.height), rt, BLACK);
    } else {
      helvCentered(helv40b, cx, BIG_Y, num, BLACK);
    }
    for (int i = 1; i < n; i++) {
      if (tag) snprintf(num, sizeof(num), "%ld (%s)", mins[i], who[i]);
      else snprintf(num, sizeof(num), "%ld", mins[i]);
      helvCentered(helv28b, cx, ROW_Y[i - 1], num, BLACK);
    }
  }

  // Column separators + bottom rule.
  for (int c = 1; c < NUM_COLS; c++)
    EPD_DrawLine(c * COL_W, 10, c * COL_W, RULE_Y - 8, BLACK);
  EPD_DrawLine(0, RULE_Y, SCREEN_W - 1, RULE_Y, BLACK);

  // Bottom line: alert ticker on the left, clock on the right.
  int clockW = clock12 ? helvTextW(helv18, clock12) : 0;
  if (clock12)
    helvDraw(helv18, SCREEN_W - clockW - 8, BOTTOM_Y, clock12, BLACK);

  if (nBlurbs > 0) {
    char line[110];
    snprintf(line, sizeof(line), "%s", blurbs[rotation % nBlurbs]);
    if (nBlurbs > 1) {
      char tag[10];
      snprintf(tag, sizeof(tag), " (%d/%d)", rotation % nBlurbs + 1, nBlurbs);
      strncat(line, tag, sizeof(line) - strlen(line) - 1);
    }
    // Truncate to fit left of the clock.
    int maxW = SCREEN_W - clockW - 32;
    int len = strlen(line);
    while (len > 0 && helvTextW(helv18, line) > maxW) line[--len] = '\0';
    helvDraw(helv18, 8, BOTTOM_Y, line, BLACK);
  }
}
