// Board layout: five equal columns -- weather, then four train columns.
//
//   ┌─────────┬─────────┬─────────┬─────────┬─────────┐
//   │   78°   │  (2/3)  │  (4/5)  │   (A)   │  (B/Q)  │  bullet
//   │ 82°/71° │ Nevins  │ Nevins  │Schermer.│ DeKalb  │  station
//   │   ☂     │    7    │    1    │    3    │    0    │  next train, big
//   │  60%    │  15 24  │   8 15  │  12 19  │   9 17  │  following trains
//   ├─────────┴─────────┴─────────┴─────────┴─────────┤
//   │ alert ticker                              3:05 PM│
//   └───────────────────────────────────────────────────┘

#include <stdio.h>
#include <string.h>
#include <math.h>

#include "display.h"
#include "EPD.h"
#include "config.h"
#include "helvfont.h"
#include "stopnames.h"

namespace {

constexpr int SCREEN_W   = 792;
constexpr int SCREEN_H   = 272;
// NUM_TRAIN_COLS is now a runtime value (from the fetched config), so the column
// count and width are computed per-render inside displayRender (numCols/colW).

constexpr int BULLET_CY  = 40;
constexpr int BULLET_R   = 31;
constexpr int STATION_TOP = 72;    // destination band: just below the bullet...
constexpr int STATION_BOT = 101;   // ...to just above the big digits
constexpr int STATION_BAND = STATION_BOT - STATION_TOP;
constexpr int BIG_Y      = 102;    // helv40b rows 102..142
constexpr int ROW_Y[3]   = {150, 180, 210};   // helv28b rows for arrivals 2-4
constexpr int RULE_Y     = 244;
constexpr int BOTTOM_Y   = 250;    // helv18 ticker/clock line

// Destination label auto-fit ladder (ascending; baked by genfont.py). The
// largest whose text fits the column width and the vertical band is used, but
// never smaller than STATION_FLOOR_IDX (helv15) -- labels too wide there are
// truncated instead of shrinking the whole set below 15px.
static const HelvFont* const STATION_FONTS[] = {&helv11, &helv15, &helv19, &helv23};
constexpr int NUM_STATION_FONTS = 4;
constexpr int STATION_FLOOR_IDX = 1;   // helv15 -- the minimum size

// Direction arrows indexed by travelDir(): 0=N, 1=E, 2=S, 3=W.
static const SymBitmap* const ARROWS[4] = {&icon_arr_n, &icon_arr_e, &icon_arr_s, &icon_arr_w};
// Small arrows for the Hero Digit / Platform Cards column headers.
static const SymBitmap* const ARROWS_SM[4] = {&icon_arrsm_n, &icon_arrsm_e,
                                              &icon_arrsm_s, &icon_arrsm_w};

// ---- Helvetica bitmap renderer (fonts generated by genfont.py) ----

int helvGlyph(const HelvFont& f, char c) {
  const char* p = strchr(f.charset, c);
  return p ? (int)(p - f.charset) : -1;
}

int helvCharW(const HelvFont& f, char c) {
  int i = helvGlyph(f, c);
  return i < 0 ? 0 : f.widths[i];
}

int helvTextW(const HelvFont& f, const char* s) {
  int w = 0;
  for (; *s; s++) w += helvCharW(f, *s);
  return w;
}

// Paints only foreground pixels; returns the advance.
int helvDrawChar(const HelvFont& f, int x, int y, char c, int color) {
  int i = helvGlyph(f, c);
  if (i < 0) return 0;
  int w = f.widths[i];
  int wbytes = (w + 7) / 8;
  const uint8_t* d = f.data + f.offsets[i];
  for (int row = 0; row < f.height; row++)
    for (int xb = 0; xb < wbytes; xb++) {
      uint8_t b = d[row * wbytes + xb];
      for (int bit = 0; b && bit < 8; bit++, b <<= 1)
        if (b & 0x80) Paint_SetPixel(x + xb * 8 + bit, y + row, color);
    }
  return w;
}

void helvDraw(const HelvFont& f, int x, int y, const char* s, int color) {
  for (; *s; s++) x += helvDrawChar(f, x, y, *s, color);
}

void helvCentered(const HelvFont& f, int cx, int y, const char* s, int color) {
  helvDraw(f, cx - helvTextW(f, s) / 2, y, s, color);
}

void drawSymbol(const SymBitmap& s, int x, int y, int color) {
  int wbytes = (s.w + 7) / 8;
  for (int row = 0; row < s.h; row++)
    for (int xb = 0; xb < wbytes; xb++) {
      uint8_t b = s.data[row * wbytes + xb];
      for (int bit = 0; b && bit < 8; bit++, b <<= 1)
        if (b & 0x80) Paint_SetPixel(x + xb * 8 + bit, y + row, color);
    }
}

// Minutes until epoch t; negative means already gone.
long minutesUntil(uint32_t t, time_t now) {
  if ((time_t)t <= now) return ((time_t)t >= now - 45) ? 0 : -1;
  return (t - now) / 60;
}

// Find a stop by id (strips the N/S suffix, binary-searches STOP_NAMES, which
// genstops.py sorts by id). Returns the entry (name + lat/lon) or nullptr.
const StopName* stopFind(const char* stopId) {
  if (!stopId || !stopId[0]) return nullptr;
  char base[8];
  size_t n = strlen(stopId);
  if (n && (stopId[n - 1] == 'N' || stopId[n - 1] == 'S')) n--;
  if (n >= sizeof(base)) n = sizeof(base) - 1;
  memcpy(base, stopId, n);
  base[n] = '\0';
  int lo = 0, hi = (int)STOP_NAMES_COUNT - 1;
  while (lo <= hi) {
    int mid = (lo + hi) / 2;
    int c = strcmp(STOP_NAMES[mid].id, base);
    if (c == 0) return &STOP_NAMES[mid];
    if (c < 0) lo = mid + 1;
    else hi = mid - 1;
  }
  return nullptr;
}

const char* stopName(const char* stopId) {
  const StopName* s = stopFind(stopId);
  return s ? s->name : "";
}

// Compass heading from one stop to another, snapped to the dominant axis:
// 0=N, 1=E, 2=S, 3=W, or -1 if either stop's coordinates are unknown. The
// feed only encodes N/S; this recovers true E/W (e.g. the 7 to Hudson Yards).
int travelDir(const char* fromId, const char* toId) {
  const StopName* a = stopFind(fromId);
  const StopName* b = stopFind(toId);
  if (!a || !b) return -1;
  float dN = b->lat - a->lat;
  float dE = (b->lon - a->lon) * cosf((a->lat + b->lat) * 0.5f * 0.017453292f);
  if (fabsf(dN) >= fabsf(dE)) return dN >= 0 ? 0 : 2;
  return dE >= 0 ? 1 : 3;
}

constexpr char DEG = '\xb0';

void hour12(int h, char* buf, size_t sz) {
  snprintf(buf, sz, "%d%s", ((h + 11) % 12) + 1, h < 12 ? "AM" : "PM");
}

// Icon + text, centered as a unit and vertically centered on cy.
void iconRow(int cx, int cy, const SymBitmap& ic, const char* text,
             const HelvFont& font, int gap = 5) {
  int tw = helvTextW(font, text);
  int x0 = cx - (ic.w + gap + tw) / 2;
  drawSymbol(ic, x0, cy - ic.h / 2, BLACK);
  helvDraw(font, x0 + ic.w + gap, cy - font.height / 2, text, BLACK);
}

// Weather column: big feels-like temperature, then rows -- wind gusts, rain
// (only if likely), UV, and Citi Bike e-bikes (only if available) -- spread
// evenly below the temperature.
void drawWeather(int cx, const WeatherInfo& wx, int ebikes) {
  if (!wx.valid) {
    helvCentered(helv28b, cx, 30, "--", BLACK);
    return;
  }
  char buf[24];
  snprintf(buf, sizeof(buf), "%d%c", wx.feels, DEG);
  helvCentered(helv40b, cx, 16, buf, BLACK);

  const SymBitmap* icons[4];
  char texts[4][20];
  int n = 0;
  icons[n] = &icon_wind; snprintf(texts[n], sizeof(texts[0]), "%d mph", wx.gusts); n++;
  if (wx.rainHour >= 0) {
    char hb[8]; hour12(wx.rainHour, hb, sizeof(hb));
    icons[n] = &sym_rain;
    snprintf(texts[n], sizeof(texts[0]), "%d%% %s", wx.rainProb, hb); n++;
  }
  icons[n] = &sym_sun; snprintf(texts[n], sizeof(texts[0]), "%d %s", wx.uv, wx.uvLevel); n++;
  if (ebikes >= 0) { icons[n] = &icon_ebike; snprintf(texts[n], sizeof(texts[0]), "%d", ebikes); n++; }

  const int top = 66, bot = RULE_Y - 12;    // 66 .. 232
  for (int i = 0; i < n; i++) {
    int cy = top + (bot - top) * (2 * i + 1) / (2 * n);
    iconRow(cx, cy, *icons[i], texts[i], helv18);
  }
}

// Copy at most the first three (space-separated) words of src into dst.
void threeWords(const char* src, char* dst, size_t dstSize) {
  size_t j = 0;
  int words = 0;
  bool prevSpace = true;
  for (size_t i = 0; src[i]; i++) {
    bool sp = (src[i] == ' ');
    if (!sp && prevSpace && ++words > 3) break;   // start of a 4th word
    prevSpace = sp;
    if (j < dstSize - 1) dst[j++] = src[i];
  }
  while (j > 0 && dst[j - 1] == ' ') j--;          // trim trailing space
  dst[j] = '\0';
}

// The largest ladder font at which EVERY label fits the column width + band,
// so all columns share one size (the size of the most-constrained label).
const HelvFont* uniformStationFont(const char labels[][48], int count, int colW) {
  int best = NUM_STATION_FONTS - 1;
  for (int c = 0; c < count; c++) {
    int idx = 0;
    for (int k = 0; k < NUM_STATION_FONTS; k++) {
      const HelvFont* f = STATION_FONTS[k];
      if (f->height <= STATION_BAND && helvTextW(*f, labels[c]) <= colW - 8) idx = k;
    }
    if (idx < best) best = idx;
  }
  if (best < STATION_FLOOR_IDX) best = STATION_FLOOR_IDX;   // 15px minimum
  return STATION_FONTS[best];
}

// ---- shared layout helpers ----------------------------------------------

void toUpper(char* s) {
  for (; *s; s++)
    if (*s >= 'a' && *s <= 'z') *s -= 32;
}

// Truncate in place until the string fits maxW at this size.
void fitText(const HelvFont& f, char* s, int maxW) {
  for (int len = strlen(s); len > 0 && helvTextW(f, s) > maxW; ) s[--len] = '\0';
}

// Outline rectangle with a pixel thickness (EPD_DrawRectangle draws 1px).
void rectOutline(int x0, int y0, int x1, int y1, int thick) {
  for (int i = 0; i < thick; i++)
    EPD_DrawRectangle(x0 + i, y0 + i, x1 - i, y1 - i, BLACK, 0);
}

struct Arrival { long mins; const char* who; };

// One column's prepared data. Every layout draws from this -- the arrival
// merge, destination lookup and direction inference happen exactly once, in
// prepareColumns(), so the layouts differ only in how they paint it.
struct ColData {
  const ColumnConfig* cc;
  char station[48];              // 3-word capped destination (or fallback)
  int dir;                       // 0=N 1=E 2=S 3=W, -1 unknown
  Arrival arr[ARRIVALS_SHOWN];
  int n;
  bool tag;                      // merged column -> tag each time with its route
};

struct Blurbs {
  const char* items[MAX_COLS];
  char fallback[MAX_COLS][44];
  int n;
};

void prepareColumns(const RouteArrivals* routes, size_t nRoutes, time_t now,
                    const RouteAlert* alerts, ColData* cols, Blurbs& bl) {
  bl.n = 0;
  for (int col = 0; col < NUM_TRAIN_COLS; col++) {
    const ColumnConfig& cc = COLUMNS[col];
    ColData& cd = cols[col];
    cd.cc = &cc;
    cd.n = 0;
    cd.dir = -1;
    cd.tag = cc.nRoutes > 1;

    // Soonest train decides the destination label and the travel direction.
    long bestMin = 100;
    const char* bestDest = "";
    const char* bestDestId = "";
    for (uint8_t ri = 0; ri < cc.nRoutes; ri++) {
      const RouteArrivals& ra = routes[cc.routeIdx[ri]];
      for (uint8_t i = 0; i < ra.count; i++) {
        long m = minutesUntil(ra.times[i], now);
        if (m < 0 || m > 99) continue;
        const char* dn = stopName(ra.dest[i]);
        if (cc.nFilter > 0) {
          bool ok = false;
          for (uint8_t k = 0; k < cc.nFilter; k++)
            if (cc.destFilter[k][0] && strcmp(cc.destFilter[k], dn) == 0) { ok = true; break; }
          if (!ok) continue;
        }
        if (m < bestMin) { bestMin = m; bestDest = dn; bestDestId = ra.dest[i]; }
      }
    }
    const char* station = (bestMin <= 99 && bestDest[0]) ? bestDest : cc.station;
    threeWords(station, cd.station, sizeof(cd.station));
    if (bestMin <= 99)
      cd.dir = travelDir(routes[cc.routeIdx[0]].stopId, bestDestId);

    // Merge the column's routes into one minute-sorted list (stable).
    for (uint8_t ri = 0; ri < cc.nRoutes; ri++) {
      const RouteArrivals& ra = routes[cc.routeIdx[ri]];
      for (uint8_t i = 0; i < ra.count; i++) {
        long m = minutesUntil(ra.times[i], now);
        if (m < 0 || m > 99) continue;
        if (cc.nFilter > 0) {
          const char* dn = stopName(ra.dest[i]);
          bool ok = false;
          for (uint8_t k = 0; k < cc.nFilter; k++)
            if (cc.destFilter[k][0] && strcmp(cc.destFilter[k], dn) == 0) { ok = true; break; }
          if (!ok) continue;
        }
        int pos = cd.n < ARRIVALS_SHOWN ? cd.n : ARRIVALS_SHOWN - 1;
        if (cd.n == ARRIVALS_SHOWN && m >= cd.arr[pos].mins) continue;
        while (pos > 0 && cd.arr[pos - 1].mins > m) { cd.arr[pos] = cd.arr[pos - 1]; pos--; }
        cd.arr[pos].mins = m;
        cd.arr[pos].who = ra.route;
        if (cd.n < ARRIVALS_SHOWN) cd.n++;
      }
    }

    if (cd.n == 0) {
      const char* blurb = nullptr;
      for (uint8_t ri = 0; ri < cc.nRoutes && !blurb; ri++) {
        const char* route = routes[cc.routeIdx[ri]].route;
        for (size_t a = 0; a < nRoutes; a++)
          if (strcmp(alerts[a].route, route) == 0 && alerts[a].text[0]) { blurb = alerts[a].text; break; }
      }
      if (!blurb) {
        snprintf(bl.fallback[bl.n], sizeof(bl.fallback[0]),
                 "No [%s] trains scheduled right now", cc.label);
        blurb = bl.fallback[bl.n];
      }
      bool dup = false;
      for (int b = 0; b < bl.n; b++) if (strcmp(bl.items[b], blurb) == 0) dup = true;
      if (!dup && bl.n < MAX_COLS) bl.items[bl.n++] = blurb;
    }
  }
}

// The alert line for the bottom bar: one blurb, cycled per refresh.
void tickerText(const Blurbs& bl, int rotation, char* out, size_t sz) {
  if (bl.n <= 0) { out[0] = '\0'; return; }
  snprintf(out, sz, "%s", bl.items[rotation % bl.n]);
  if (bl.n > 1) {
    char t[12];
    snprintf(t, sizeof(t), " (%d/%d)", rotation % bl.n + 1, bl.n);
    strncat(out, t, sz - strlen(out) - 1);
  }
}

// ---- layout R: Refined Signage -------------------------------------------

void renderRefined(const ColData* cols, const Blurbs& bl, const WeatherInfo& wx,
                   int rotation, const char* clock12, const char* date_str, int ebikes) {
  const int numCols = NUM_TRAIN_COLS + 1;
  const int colW = SCREEN_W / numCols;

  rectOutline(2, 2, SCREEN_W - 3, SCREEN_H - 3, 3);
  drawWeather(colW / 2, wx, ebikes);

  char labels[MAX_COLS][48];
  for (int col = 0; col < NUM_TRAIN_COLS; col++)
    snprintf(labels[col], sizeof(labels[0]), "%s", cols[col].station);
  const HelvFont* sfont = uniformStationFont(labels, NUM_TRAIN_COLS, colW);
  int stationY = STATION_TOP + (STATION_BAND - sfont->height) / 2;

  for (int col = 0; col < NUM_TRAIN_COLS; col++) {
    const ColData& cd = cols[col];
    int cx = (col + 1) * colW + colW / 2;

    EPD_DrawCircle(cx, BULLET_CY, BULLET_R, BLACK, 1);
    helvCentered(helv28b, cx, BULLET_CY - helv28b.height / 2, cd.cc->label, WHITE);
    if (cd.dir >= 0) {
      const SymBitmap& a = *ARROWS[cd.dir];
      drawSymbol(a, cx - BULLET_R - 6 - a.w, BULLET_CY - a.h / 2, BLACK);
    }

    char stbuf[48];
    snprintf(stbuf, sizeof(stbuf), "%s", cd.station);
    fitText(*sfont, stbuf, colW - 8);
    helvCentered(*sfont, cx, stationY, stbuf, BLACK);

    if (cd.n == 0) {
      EPD_DrawRectangle(cx - 16, BIG_Y + 18, cx + 16, BIG_Y + 22, BLACK, 1);
      helvCentered(helv18, cx, ROW_Y[0] + 4, "no service", BLACK);
      continue;
    }

    char num[8], suffix[12];
    for (int i = 0; i < cd.n; i++) {
      const HelvFont& numFont = (i == 0) ? helv40b : helv28b;
      int y = (i == 0) ? BIG_Y : ROW_Y[i - 1];
      int gap = (i == 0) ? 6 : 4;
      snprintf(num, sizeof(num), "%ld", cd.arr[i].mins);
      if (cd.tag) snprintf(suffix, sizeof(suffix), "min (%s)", cd.arr[i].who);
      else        snprintf(suffix, sizeof(suffix), "min");
      int wn = helvTextW(numFont, num), ws = helvTextW(helv18, suffix);
      int xx = cx - (wn + gap + ws) / 2;
      helvDraw(numFont, xx, y, num, BLACK);
      helvDraw(helv18, xx + wn + gap, y + (numFont.height - helv18.height), suffix, BLACK);
    }
  }

  for (int c = 1; c < numCols; c++)
    EPD_DrawLine(c * colW, 14, c * colW, RULE_Y - 8, BLACK);
  EPD_DrawLine(12, RULE_Y, SCREEN_W - 13, RULE_Y, BLACK);
  EPD_DrawLine(12, RULE_Y + 3, SCREEN_W - 13, RULE_Y + 3, BLACK);

  char right[48];
  if (date_str && date_str[0]) snprintf(right, sizeof(right), "%s  %s", date_str, clock12 ? clock12 : "");
  else                         snprintf(right, sizeof(right), "%s", clock12 ? clock12 : "");
  int rw = helvTextW(helv18, right);
  if (right[0]) helvDraw(helv18, SCREEN_W - rw - 14, BOTTOM_Y, right, BLACK);

  char line[110];
  tickerText(bl, rotation, line, sizeof(line));
  if (line[0]) {
    fitText(helv18, line, SCREEN_W - rw - 40);
    helvDraw(helv18, 14, BOTTOM_Y, line, BLACK);
  }
}

// ---- layout H: Hero Digit ------------------------------------------------

void renderHero(const ColData* cols, const Blurbs& bl, const WeatherInfo& wx,
                int rotation, const char* clock12, const char* date_str, int ebikes) {
  const int nCols = NUM_TRAIN_COLS > 0 ? NUM_TRAIN_COLS : 1;
  const int colW = SCREEN_W / nCols;

  // Weather compressed to a single strip across the top.
  if (wx.valid) {
    char temp[16];
    snprintf(temp, sizeof(temp), "%d%c", wx.feels, DEG);
    helvDraw(helv32b, 14, 6, temp, BLACK);
    int x = 14 + helvTextW(helv32b, temp) + 22;
    char bit[24];
    snprintf(bit, sizeof(bit), "%d MPH", wx.gusts);
    helvDraw(helv13b, x, 18, bit, BLACK); x += helvTextW(helv13b, bit) + 20;
    if (wx.rainHour >= 0) {
      char hb[8]; hour12(wx.rainHour, hb, sizeof(hb));
      snprintf(bit, sizeof(bit), "%d%% @ %s", wx.rainProb, hb);
      helvDraw(helv13b, x, 18, bit, BLACK); x += helvTextW(helv13b, bit) + 20;
    }
    snprintf(bit, sizeof(bit), "UV %d", wx.uv);
    helvDraw(helv13b, x, 18, bit, BLACK); x += helvTextW(helv13b, bit) + 20;
    if (ebikes >= 0) {
      snprintf(bit, sizeof(bit), "%d E-BIKES", ebikes);
      helvDraw(helv13b, x, 18, bit, BLACK);
    }
  }

  const char* clk = clock12 ? clock12 : "";
  int rw = helvTextW(helv19b, clk);
  helvDraw(helv19b, SCREEN_W - rw - 14, 14, clk, BLACK);
  if (date_str && date_str[0]) {
    char d[32];
    snprintf(d, sizeof(d), "%s", date_str);
    toUpper(d);
    int dw = helvTextW(helv12b, d);
    helvDraw(helv12b, SCREEN_W - rw - dw - 24, 18, d, BLACK);
  }
  EPD_DrawRectangle(0, 56, SCREEN_W - 1, 60, BLACK, 1);

  for (int col = 0; col < NUM_TRAIN_COLS; col++) {
    const ColData& cd = cols[col];
    int x0 = col * colW;
    int cx = x0 + colW / 2;
    const int hy = 82, r = 13;

    int ax = x0 + 8, aw = 0;
    if (cd.dir >= 0) {
      const SymBitmap& a = *ARROWS_SM[cd.dir];
      aw = a.w;
      drawSymbol(a, ax, hy - a.h / 2, BLACK);
    }
    int bx = ax + aw + (aw ? 7 : 0) + r;
    EPD_DrawCircle(bx, hy, r, BLACK, 1);
    const HelvFont& lab = (strlen(cd.cc->label) > 2) ? helv12b : helv15b;
    helvCentered(lab, bx, hy - lab.height / 2, cd.cc->label, WHITE);

    int dx = bx + r + 6;
    char dest[48];
    snprintf(dest, sizeof(dest), "%s", cd.station);
    toUpper(dest);
    fitText(helv12b, dest, x0 + colW - dx - 8);
    helvDraw(helv12b, dx, hy - helv12b.height / 2, dest, BLACK);

    if (cd.n == 0) {
      EPD_DrawRectangle(cx - 18, 150, cx + 18, 155, BLACK, 1);
      helvCentered(helv15b, cx, 170, "no service", BLACK);
      continue;
    }

    char hero[8];
    snprintf(hero, sizeof(hero), "%ld", cd.arr[0].mins);
    helvCentered(helv74b, cx, 104, hero, BLACK);

    char unit[16];
    if (cd.tag) snprintf(unit, sizeof(unit), "MIN (%s)", cd.arr[0].who);
    else        snprintf(unit, sizeof(unit), "MIN");
    helvCentered(helv13b, cx, 190, unit, BLACK);

    if (cd.n > 1) {
      char rest[48] = "then ";
      for (int i = 1; i < cd.n; i++) {
        char piece[20];
        if (cd.tag) snprintf(piece, sizeof(piece), "%s%ld (%s)", i > 1 ? ", " : "",
                             cd.arr[i].mins, cd.arr[i].who);
        else        snprintf(piece, sizeof(piece), "%s%ld", i > 1 ? ", " : "", cd.arr[i].mins);
        strncat(rest, piece, sizeof(rest) - strlen(rest) - 1);
      }
      fitText(helv15b, rest, colW - 10);
      helvCentered(helv15b, cx, 210, rest, BLACK);
    }
  }

  EPD_DrawLine(0, 240, SCREEN_W - 1, 240, BLACK);
  char line[110];
  tickerText(bl, rotation, line, sizeof(line));
  if (line[0]) {
    fitText(helv14, line, SCREEN_W - 28);
    helvDraw(helv14, 14, 248, line, BLACK);
  }
}

// ---- layout P: Platform Cards --------------------------------------------

void renderCards(const ColData* cols, const Blurbs& bl, const WeatherInfo& wx,
                 int rotation, const char* clock12, const char* date_str, int ebikes) {
  const int n = NUM_TRAIN_COLS + 1;            // + weather card
  const int gap = 10, margin = 14;
  const int cardW = (SCREEN_W - margin * 2 - gap * (n - 1)) / n;
  const int cardTop = 14, cardBot = 222;

  // ---- weather card ----
  int x = margin;
  rectOutline(x, cardTop, x + cardW, cardBot, 2);
  if (date_str && date_str[0]) {
    char d[32];
    snprintf(d, sizeof(d), "%s", date_str);
    toUpper(d);
    helvDraw(helv13b, x + 10, cardTop + 8, d, BLACK);
  }
  if (wx.valid) {
    char temp[16];
    snprintf(temp, sizeof(temp), "%d%c", wx.feels, DEG);
    helvCentered(helv32b, x + cardW / 2, cardTop + 34, temp, BLACK);

    const SymBitmap* icons[4];
    char texts[4][20];
    int rows = 0;
    icons[rows] = &icon_wind; snprintf(texts[rows], sizeof(texts[0]), "%d mph", wx.gusts); rows++;
    if (wx.rainHour >= 0) {
      char hb[8]; hour12(wx.rainHour, hb, sizeof(hb));
      icons[rows] = &sym_rain;
      snprintf(texts[rows], sizeof(texts[0]), "%d%% %s", wx.rainProb, hb); rows++;
    }
    icons[rows] = &sym_sun;
    snprintf(texts[rows], sizeof(texts[0]), "%d %s", wx.uv, wx.uvLevel); rows++;
    if (ebikes >= 0) {
      icons[rows] = &icon_ebike;
      snprintf(texts[rows], sizeof(texts[0]), "%d", ebikes); rows++;
    }
    const int top = cardTop + 84, bot = cardBot - 14;
    for (int i = 0; i < rows; i++) {
      int cy = top + (bot - top) * (2 * i + 1) / (2 * rows);
      drawSymbol(*icons[i], x + 12, cy - icons[i]->h / 2, BLACK);
      helvDraw(helv12b, x + 12 + icons[i]->w + 8, cy - helv12b.height / 2, texts[i], BLACK);
    }
  }

  // ---- one card per train column ----
  for (int col = 0; col < NUM_TRAIN_COLS; col++) {
    const ColData& cd = cols[col];
    x = margin + (col + 1) * (cardW + gap);
    rectOutline(x, cardTop, x + cardW, cardBot, 2);

    int chipW = 18 + helvTextW(helv13b, cd.cc->label);
    EPD_DrawRectangle(x + 10, cardTop + 8, x + 10 + chipW, cardTop + 28, BLACK, 1);
    helvCentered(helv13b, x + 10 + chipW / 2, cardTop + 18 - helv13b.height / 2,
                 cd.cc->label, WHITE);
    if (cd.dir >= 0) {
      const SymBitmap& a = *ARROWS_SM[cd.dir];
      drawSymbol(a, x + cardW - 10 - a.w, cardTop + 18 - a.h / 2, BLACK);
    }

    char dest[48];
    snprintf(dest, sizeof(dest), "%s", cd.station);
    toUpper(dest);
    fitText(helv12b, dest, cardW - 20);
    helvDraw(helv12b, x + 10, cardTop + 34, dest, BLACK);

    if (cd.n == 0) {
      EPD_DrawRectangle(x + 12, cardTop + 96, x + 44, cardTop + 101, BLACK, 1);
      helvDraw(helv12b, x + 12, cardTop + 116, "no service", BLACK);
      continue;
    }

    char big[8];
    snprintf(big, sizeof(big), "%ld", cd.arr[0].mins);
    helvDraw(helv48b, x + 12, cardTop + 50, big, BLACK);
    char unit[16];
    if (cd.tag) snprintf(unit, sizeof(unit), "MIN (%s)", cd.arr[0].who);
    else        snprintf(unit, sizeof(unit), "MIN");
    helvDraw(helv12b, x + 12, cardTop + 112, unit, BLACK);

    int cy = cardTop + 134;
    for (int i = 1; i < cd.n; i++) {
      char txt[20];
      if (cd.tag) snprintf(txt, sizeof(txt), "%ld MIN (%s)", cd.arr[i].mins, cd.arr[i].who);
      else        snprintf(txt, sizeof(txt), "%ld MIN", cd.arr[i].mins);
      int w = helvTextW(helv13b, txt) + 18;
      if (w > cardW - 24) w = cardW - 24;
      EPD_DrawRectangle(x + 12, cy, x + 12 + w, cy + 24, BLACK, 0);
      fitText(helv13b, txt, w - 8);
      helvCentered(helv13b, x + 12 + w / 2, cy + 12 - helv13b.height / 2, txt, BLACK);
      cy += 30;
    }
  }

  // ---- footer strip, below the cards (never overlapping them) ----
  const int fy0 = 232, fy1 = 258;
  EPD_DrawRectangle(margin, fy0, SCREEN_W - margin, fy1, BLACK, 0);
  const char* clk = clock12 ? clock12 : "";
  int rw = helvTextW(helv14, clk);
  helvDraw(helv14, SCREEN_W - margin - rw - 10, fy0 + 6, clk, BLACK);
  char line[110];
  tickerText(bl, rotation, line, sizeof(line));
  if (line[0]) {
    fitText(helv14, line, SCREEN_W - margin * 2 - rw - 34);
    helvDraw(helv14, margin + 10, fy0 + 6, line, BLACK);
  }
}

}  // namespace

void displayRender(const RouteArrivals* routes, size_t nRoutes, time_t now,
                   const RouteAlert* alerts, const WeatherInfo& wx,
                   int rotation, const char* clock12, int ebikes,
                   const char* date_str) {
  Paint_Clear(WHITE);

  // The arrival merge, destination lookup and direction inference happen once
  // here; the selected layout only decides how that data gets painted.
  ColData cols[MAX_COLS];
  Blurbs bl;
  prepareColumns(routes, nRoutes, now, alerts, cols, bl);

  switch (LAYOUT) {
    case 'H': renderHero(cols, bl, wx, rotation, clock12, date_str, ebikes); break;
    case 'P': renderCards(cols, bl, wx, rotation, clock12, date_str, ebikes); break;
    default:  renderRefined(cols, bl, wx, rotation, clock12, date_str, ebikes); break;
  }
}
