# Generates helvfont.h: Helvetica bitmap fonts + weather symbols for the
# SubwayBoard e-ink display. 1bpp, row-major, MSB = leftmost pixel.
from PIL import Image, ImageDraw, ImageFont

HELV = '/System/Library/Fonts/Helvetica.ttc'
SYM  = '/System/Library/Fonts/Apple Symbols.ttf'

ASCII = ''.join(chr(c) for c in range(32, 127))
DEG = '\xb0'   # degree sign, stored at charset byte 0xB0

def render_font(name, path, index, px, charset, thresh=110):
    font = ImageFont.truetype(path, px, index=index)
    ascent, descent = font.getmetrics()
    H = ascent + descent
    widths, offsets, data = [], [], bytearray()
    for ch in charset:
        adv = max(1, round(font.getlength(ch)))
        img = Image.new('L', (adv + 8, H), 0)
        ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=255)
        # crop to advance width (keeps natural side bearings)
        wbytes = (adv + 7) // 8
        offsets.append(len(data))
        for y in range(H):
            for xb in range(wbytes):
                b = 0
                for bit in range(8):
                    x = xb * 8 + bit
                    if x < adv and img.getpixel((x, y)) >= thresh:
                        b |= 0x80 >> bit
                data.append(b)
        widths.append(adv)
    return dict(name=name, H=H, charset=charset, widths=widths, offsets=offsets, data=data)

def render_symbol(name, ch, px, thresh=110):
    font = ImageFont.truetype(SYM, px)
    bbox = font.getbbox(ch)
    w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
    img = Image.new('L', (w, h), 0)
    ImageDraw.Draw(img).text((-bbox[0], -bbox[1]), ch, font=font, fill=255)
    wbytes = (w + 7) // 8
    data = bytearray()
    for y in range(h):
        for xb in range(wbytes):
            b = 0
            for bit in range(8):
                x = xb * 8 + bit
                if x < w and img.getpixel((x, y)) >= thresh:
                    b |= 0x80 >> bit
            data.append(b)
    on = sum(bin(b).count('1') for b in data)
    print(f"symbol {name}: {w}x{h}, {on} px on")
    return dict(name=name, w=w, h=h, data=data)

fonts = [
    render_font('helv18',  HELV, 0, 18, ASCII + DEG),
    render_font('helv28b', HELV, 1, 28, ASCII + DEG),
    render_font('helv40b', HELV, 1, 40, '0123456789/' + DEG),
]
symbols = [
    render_symbol('sym_umbrella',  '☂', 44),   # ☂
    render_symbol('sym_snow',      '❄', 44),   # ❄
    render_symbol('sym_storm',     '⛈', 48),   # ⛈
]

out = open('/Users/peterzelles/SubwayBoard/helvfont.h', 'w')
out.write('// Generated by genfont.py -- Helvetica bitmaps + weather symbols.\n')
out.write('// 1bpp, row-major, MSB = leftmost pixel. Do not edit by hand.\n#pragma once\n#include <stdint.h>\n\n')
out.write('struct HelvFont { uint8_t height; const char* charset; const uint8_t* widths;\n'
          '                  const uint16_t* offsets; const uint8_t* data; };\n\n')
out.write('struct SymBitmap { uint8_t w, h; const uint8_t* data; };\n\n')
for f in fonts:
    n = f['name']
    cs = ''.join('\\x%02x' % ord(c) for c in f['charset'])
    out.write(f'static const char {n}_charset[] = "{cs}";\n')
    out.write(f'static const uint8_t {n}_widths[] = {{{",".join(map(str, f["widths"]))}}};\n')
    out.write(f'static const uint16_t {n}_offsets[] = {{{",".join(map(str, f["offsets"]))}}};\n')
    out.write(f'static const uint8_t {n}_data[] = {{{",".join(map(str, f["data"]))}}};\n')
    out.write(f'static const HelvFont {n} = {{{f["H"]}, {n}_charset, {n}_widths, {n}_offsets, {n}_data}};\n\n')
for s in symbols:
    n = s['name']
    out.write(f'static const uint8_t {n}_data[] = {{{",".join(map(str, s["data"]))}}};\n')
    out.write(f'static const SymBitmap {n} = {{{s["w"]}, {s["h"]}, {n}_data}};\n\n')
out.close()
print('fonts:', [(f['name'], f['H'], len(f['charset'])) for f in fonts])
print('wrote helvfont.h')
