# Generates stopnames.h: MTA stop_id (direction suffix stripped) -> station
# name, so the board can show a train's destination (its terminal) on the
# device. Reads the emulator's cached stops.txt (emulator/stops_cache.csv);
# if that's missing, downloads the MTA static GTFS once.
#
#   python3 genstops.py
import csv
import io
import os
import ssl
import urllib.request
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, 'emulator', 'stops_cache.csv')
GTFS_ZIP = 'https://rrgtfsfeeds.s3.amazonaws.com/gtfs_subway.zip'


def load_rows():
    if os.path.exists(CACHE):
        with open(CACHE, 'r', encoding='utf-8') as f:
            return f.read()
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    raw = urllib.request.urlopen(
        urllib.request.Request(GTFS_ZIP, headers={'User-Agent': 'x'}),
        timeout=30, context=ctx).read()
    return zipfile.ZipFile(io.BytesIO(raw)).read('stops.txt').decode('utf-8')


# Map each base stop id (no N/S suffix) to (station name, lat, lon).
names = {}
coords = {}
for row in csv.DictReader(io.StringIO(load_rows())):
    sid = row['stop_id']
    base = sid[:-1] if sid and sid[-1] in 'NS' else sid
    names.setdefault(base, row['stop_name'])
    try:
        coords.setdefault(base, (float(row['stop_lat']), float(row['stop_lon'])))
    except (ValueError, KeyError):
        pass


def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


out = open(os.path.join(HERE, 'stopnames.h'), 'w')
out.write('// Generated by genstops.py -- MTA stop_id (direction suffix stripped)\n')
out.write('// -> station name + lat/lon (destination label + direction arrow).\n')
out.write('// Sorted by id (binary search in display.cpp). Do not edit by hand.\n')
out.write('#pragma once\n#include <stdint.h>\n\n')
out.write('struct StopName { const char* id; const char* name; float lat; float lon; };\n\n')
out.write('static const StopName STOP_NAMES[] = {\n')
for base in sorted(names):
    lat, lon = coords.get(base, (0.0, 0.0))
    out.write('  {"%s", "%s", %.5ff, %.5ff},\n' % (esc(base), esc(names[base]), lat, lon))
out.write('};\n')
out.write('static const uint16_t STOP_NAMES_COUNT = %d;\n' % len(names))
out.close()
print('wrote stopnames.h with %d stops (+coords)' % len(names))
