# Generates stopnames.h: MTA stop_id (direction suffix stripped) -> station
# name, so the board can show a train's destination (its terminal) on the
# device. Covers all three agencies -- subway, LIRR ("L" prefix) and Metro-North
# ("M" prefix); see emulator/stops.py for why rail ids are namespaced. Reads the
# emulator's combined cache (emulator/stops_cache_all.csv); if that's missing,
# downloads each agency's static GTFS once.
#
#   python3 genstops.py
import csv
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, 'emulator', 'stops_cache_all.csv')
sys.path.insert(0, os.path.join(HERE, 'emulator'))
import stops as stops_mod  # noqa: E402  (shares one source list with the emulator)


def load_rows():
    if os.path.exists(CACHE):
        with open(CACHE, 'r', encoding='utf-8') as f:
            return f.read()
    text = stops_mod.fetch_combined()
    with open(CACHE, 'w', encoding='utf-8') as f:
        f.write(text)
    return text


# Map each base stop id (subway N/S suffix stripped) to (station name, lat, lon).
names = {}
coords = {}
for row in csv.DictReader(io.StringIO(load_rows())):
    sid = row['stop_id']
    base = stops_mod._base(sid)
    names.setdefault(base, row['stop_name'])
    try:
        coords.setdefault(base, (float(row['stop_lat']), float(row['stop_lon'])))
    except (ValueError, KeyError):
        pass


def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


out = open(os.path.join(HERE, 'stopnames.h'), 'w')
out.write('// Generated by genstops.py -- MTA stop_id (direction suffix stripped)\n')
out.write('// -> station name + lat/lon (destination label + direction arrow).\n')
out.write('// Subway ids are bare and numeric; LIRR ids carry an "L" prefix and\n')
out.write('// Metro-North ids an "M", because the three agencies reuse each\n')
out.write('// other\'s numbers (LIRR 1 = Albertson, MNR 1 = Grand Central).\n')
out.write('// Sorted by id (binary search in display.cpp). Do not edit by hand.\n')
out.write('#pragma once\n#include <stdint.h>\n\n')
out.write('struct StopName { const char* id; const char* name; float lat; float lon; };\n\n')
out.write('static const StopName STOP_NAMES[] = {\n')
for base in sorted(names):
    lat, lon = coords.get(base, (0.0, 0.0))
    out.write('  {"%s", "%s", %.5ff, %.5ff},\n' % (esc(base), esc(names[base]), lat, lon))
out.write('};\n')
out.write('static const uint16_t STOP_NAMES_COUNT = %d;\n' % len(names))
out.close()
print('wrote stopnames.h with %d stops (+coords)' % len(names))
